#!/usr/bin/env bash
# build-installer.sh — package the CLI (cli/) into a single self-contained
# dist/install.sh that users can `curl -LsSf <url> | sh`.
#
# The CLI source is embedded as a base64 tarball in a shell variable, so the
# installer works even when piped to sh (where $0 is not a seekable file).
# Re-run this whenever the CLI source changes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="dist/install.sh"
mkdir -p dist

echo "Packaging cli/ …"
TARBALL="$(mktemp -t learn-cli.XXXXXX.tgz)"
# Only ship what the build needs — no .venv, caches, or dist artifacts.
tar czf "$TARBALL" --exclude='__pycache__' --exclude='*.pyc' -C cli pyproject.toml README.md src
PAYLOAD="$(base64 < "$TARBALL" | tr -d '\n')"
rm -f "$TARBALL"
echo "Payload: $(printf '%s' "$PAYLOAD" | wc -c | tr -d ' ') base64 bytes"

# --- assemble dist/install.sh: header + PAYLOAD line + footer ---------------
{
cat <<'HEADER'
#!/bin/sh
# learn — installer (self-contained). GENERATED by scripts/build-installer.sh.
# Do not edit by hand; re-run the build script instead.
#
#   curl -LsSf <url>/install.sh | sh
#
# Env overrides:
#   LEARN_API_URL      API base URL to bake into config (default: http://localhost:3000)
#   LEARN_CONFIG_DIR   config dir (default: ~/.config/learn)
set -eu

API_URL_DEFAULT="http://localhost:3000"

info() { printf '\033[1;36m=>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$1" >&2; }
err()  { printf '\033[1;31merror:\033[0m %s\n' "$1" >&2; exit 1; }

ensure_cmd() { command -v "$1" >/dev/null 2>&1 || err "'$1' is required but not found."; }

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then return; fi
  info "uv not found — installing it from astral.sh …"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  # Make uv visible to the rest of this script without a new shell.
  [ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env" || true
  export PATH="$HOME/.local/bin:$PATH"
  command -v uv >/dev/null 2>&1 || err "uv install failed; see https://docs.astral.sh/uv/"
}

# Portable base64 decode (GNU uses -d, BSD/macOS historically -D).
if printf '' | base64 -d >/dev/null 2>&1; then B64D="base64 -d"; else B64D="base64 -D"; fi

HEADER

printf "PAYLOAD='%s'\n\n" "$PAYLOAD"

cat <<'FOOTER'
main() {
  ensure_cmd curl
  ensure_cmd tar
  ensure_uv

  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT INT TERM

  info "Unpacking learn …"
  printf '%s' "$PAYLOAD" | $B64D | tar xzf - -C "$tmp"

  info "Installing the 'learn' command (isolated environment, via uv tool) …"
  uv tool install --force "$tmp"

  # Make sure uv's tool bin dir is on PATH for future shells.
  uv tool update-shell >/dev/null 2>&1 || true

  api="${LEARN_API_URL:-$API_URL_DEFAULT}"
  cfg_dir="${LEARN_CONFIG_DIR:-$HOME/.config/learn}"
  mkdir -p "$cfg_dir"
  cat > "$cfg_dir/config.json" <<EOF
{
  "api_url": "$api"
}
EOF
  info "API URL set to $api  ($cfg_dir/config.json)"

  echo
  info "Done — 'learn' is installed."
  if ! command -v learn >/dev/null 2>&1; then
    warn "Open a new terminal (or 'source' your shell rc) so 'learn' is on your PATH."
  fi
  echo
  echo "  Try:"
  echo "    learn log \"grep -rEn 'TODO' --include='*.py' .\""
  echo "    learn find \"search python files for a pattern\""
  echo "    learn score"
  echo
}

main
FOOTER
} > "$OUT"

chmod +x "$OUT"
echo "Wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
